branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pwd
- pip install -r requirements.txt --use-mirrors
- pwd
- git clone https://github.com/trackreco/pelican-themes.git
- git clone --recursive https://github.com/getpelican/pelican-plugins
- pwd
- ls
- wget http://www.tipue.com/search/tipuesearch.zip
- unzip tipuesearch.zip
- cp -r Tipue\ Search\ 5.0/tipuesearch pelican-themes/static/
notifications:
  email:
    on_success: always
    on_failure: always
script:
- make html
env:
  global:
    secure: CVPOTSgsCWPlm42JC7Oy7SlPOPmVHk7GiwxN10E30yW/J0WXeTq5cU3WAhVOQ+b/0kSx42g/SKiM7TTWoKqCrHAEQheHc1EDzSpmzW2Nq/9v4hPfNWBc7SzhV2dInoJeh04+Dc6+XCd2/FCFN6Lw1K9VklZXL3bdFhNZGq7fdeA088AsifNB7zjLikzrlZvjF1TmIe+nFg/WlXvRXm+xlohP26knZDAE2FMp6fLFivHunTXw7HStkSNv57Ep3J7oCcFtwxKsvlj+bJHebroTyTS1DFRU9fwicvsQQ3NK9fOlHSsURgYWTOYVQK4i/Lu5o2FBHIM9ORNPxJt7eLZT7RJgB9Dz7fOjRtZAMhPqFjKUBaiqlBINUY8eBDCHhPQVvP3siMvcZQkBWdAyCpg9gH/8JodGty9kf0dFrNCN2WYLYoUtFqVdtrU118ytukSehXU5feehfi9G8f/n85DCAizJ8FV/2sl1iKIvz3jpIQYtU2DQCFyFtkEM/5RMq+heFA+Uzrnvn/MFdRlmPEWzJrAAedCgLU5CkRmywQA8p0WVfujwG8HcP/eefh5MFJIQPxr0AWr+agzUqJgWvdffQdBFwjHHqUQJpws1LNNcILRahZvEO5CGFS31xLQiJx6NDZWaERGHS3OowMk+WhWVqMjFIZNZrf7pHBmR7dH4zDQ=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
