branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pwd
- pip install -r requirements.txt --use-mirrors
- pwd
- git clone https://github.com/trackreco/pelican-themes.git
- git clone --recursive https://github.com/getpelican/pelican-plugins
- pwd
- ls
- wget http://www.tipue.com/search/tipuesearch.zip
- unzip tipuesearch.zip
- cp -r Tipue\ Search\ 5.0/tipuesearch pelican-themes/static/
notifications:
  email:
    on_success: always
    on_failure: always
script:
- make html
env:
  global:
  - secure: DDDCqhKhqDMdwxBG/FdMzlB/sgj4rAk11vkWDjNotsLZUXKsoIF8qCypPYOx1GOCnA0XQXOnNot2doiBnYs++iplP2iUCNCxn7J9a35l8VvO47SPD34QBu+A0uralx9VztU2D6nQtHS7c9FqhE4+njCHVAzbCf+s/97c1+v+q1ZdbPrHw86C7JSx2oa5/zasdwdqDeiuj17EEMZjPJkUjjh9wLODql33ASw6SY8kE6tWWzWuLJ9wp38iCArWUJAwdfYwvEfiBc/F6JtZjaWMttJQU2PcFeCNGTdBwVSJ9cw15dJZWnNk28ah06wG+wSvovi7ORHhMCiofktNcwTL0rpekAF7alMqGJOcDQ61CtT0GJg3G3Lw2x8QOBmBHYWonBTEkrYP7l/rI0DXD2kJrpvX8bQle9pyrg80EF75EZILR8U9HrFyYnhgbMALyBWa1GmY2tDwOkHf71f9tAzHklz2cwi2yi0JwYK8Dz6Kfi1vICs0j6Nrpz0zffPz9qcL0hop06xdSAysF+F4i1KmpJTUwdb/VHLHJWcp5R6y2GDDI6Y1QOaFbuE60LciNaR35RU/0Fqc49ID4sUdgtafsu/ai3fElyiXF+7LHeZZEGLDerABaEy1IlGc6StG0eouNUfzeMAQHV1akbTvS8arAULsSXAUtvtJuo/h1npHnek=
  - secure: Tn2BSwEQJQoIeo3dLRwiy2qSucEMifip5PLrBH0O+zPNhlhyfkfkrIFAwTlIrc+Wp9Gpayu9O45FVeNppmo1rE5jKvYrXJVz+jMYugMDixf7eNdn3HbUKR8tDHTTulOJYjRJM7KOOfJ/N6XEinVMkt5PeryIp50fiJZ9plkyTSeWFMljynVlsZZfTJuWEnl02s33DqZQFF98KcUPoX/PUmHmPdsuBraBwhobY+AuP9Xr95/VkcOk2obWaHZx1mHt6zF4yldXOERSHy+R0qus6g9N32CNi/VGT0735a6jPo7cNyeSlFodIwzFUfcQmPNEP3fPH+swG3GVKZXHJQrjoLqgRmtVcWSy0kbiJOEEma2ClzfWQFqCodeNirruHrAQiz0TVn6cGPGwlEuDpKuvJLS8GqBZXoU8N27L3bv0rKk5GKs9RoCI9GxbYu1RPpmP4c0YgE4e1sBqkijJWjYRdxGhTRCTxiUzZujIV5KlKZ5uq7uWEW/TJ6+rG9HdDASMR8ealMdfOFCcH7cqfsM0vhfrUqOMulyzEvCklm5w60YRzgtqIIDubGONy/mRVXKF+uDwWdXawRvuJq5cF3LuOKuObCMYM5quebeBBR+dBCJick3TYZnF9Hc8hdvvDJMzMRntx0ne1jrnQIAL19/V1HuYZs4Pla7nvhUHZWf0oIY=
before_install:
- git submodule update --init --recursive
after_success: bash deploy.sh
